name: Auto Test

on:
  push:
    branches:
      - autoreplit
      - stable
  pull_request:
    branches:
      - autoreplit
      - stable

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_ENCRYPTION_KEY: ${{ secrets.DATABASE_ENCRYPTION_KEY }}
      no_warning: false
      debug: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask App
      run: |
        no-warning=$no_warning debug=$debug DATABASE_ENCRYPTION_KEY=$DATABASE_ENCRYPTION_KEY python main.py &

    - name: Wait for Flask to start
      run: sleep 4

    - name: Test Flask App
      run: |
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8080

    - name: Stop Flask App
      run: |
        pkill -f "python main.py"

    - name: Check test result
      id: test_result
      run: echo "::set-output name=status::$(if [ ${{steps.test.stdout}} -eq 200 ]; then echo 'success'; else echo 'failure'; fi)"

    - name: Set GitHub status
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const status = '${{ steps.test_result.outputs.status }}';
          if (status === 'success') {
            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Test Flask App',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Test Result',
                summary: 'Tests passed successfully.',
              }
            });
          } else {
            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Test Flask App',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'failure',
              output: {
                title: 'Test Result',
                summary: 'Tests failed.',
              }
            });
          }
